 = sFlosers

FLAG = -Wall -Wextra -Werror -std=c++98

CC = c++

SRC = main.cpp

OBJ = $(SRC:.cpp=.o)

all: $()

%.o:%.cpp
	$(CC) $(FLAG) -c $< -o $@

$():$(OBJ)
	$(CC) $(FLAG) $(OBJ) -o $()

clean:
	rm -rf $(OBJ)

fclean: clean
	rm -rf $()

run: all
	@./$()

re: clean fclean

.PHONY: all re fclean clean